# Generated by Django 5.2 on 2025-05-10 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_type', models.CharField(blank=True, max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='sample_qrcodes/')),
                ('test_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='laboratory.testorder')),
            ],
        ),
    ]
