# Generated by Django 5.2 on 2025-07-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('blood', 'Blood'), ('urine', 'Urine'), ('microbio', 'Microbiology')], max_length=50),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('cbc', 'CBC'), ('chemistry', 'Chemistry'), ('culture', 'Culture')], max_length=50),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='tube_type',
            field=models.CharField(blank=True, choices=[('serum', 'Serum (Red-top)'), ('edta', 'EDTA (Purple)'), ('citrate', 'Citrate (Blue)')], help_text='Tube required for the primary sample', max_length=20),
        ),
        migrations.AddField(
            model_name='testorder',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testorder',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testorder',
            name='tube_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
