# Generated by Django 5.2.4 on 2025-08-11 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labrequest_category_labrequest_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['category', 'subcategory', 'english_name']},
        ),
        migrations.RemoveField(
            model_name='test',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='test',
            name='normal_range',
        ),
        migrations.AddField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(blank=True, choices=[('blood', 'Blood'), ('urine', 'Urine'), ('microbio', 'Microbiology')], max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='ref_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='ref_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='tube_type',
            field=models.CharField(choices=[('serum', 'Serum (Red-top)'), ('edta', 'EDTA (Purple)'), ('citrate', 'Citrate (Blue)'), ('urine', 'Urine Cup')], default='serum', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='groups', to='laboratory.test'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_orders', to='laboratory.testgroup'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='orders', to='laboratory.test'),
        ),
    ]
