# Generated by Django 5.2.4 on 2025-08-12 16:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_testresult'),
        ('manager', '0021_patientreportsettings_show_ros_ent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['category', 'english_name']},
        ),
        migrations.AlterModelOptions(
            name='testorder',
            options={},
        ),
        migrations.RenameField(
            model_name='labrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='testorder',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='tube_type',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='qr_code',
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('english_name', 'category')},
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='group',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='token',
        ),
        migrations.AddField(
            model_name='labrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_dispatched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='result_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('boolean', 'Positive/Negative'), ('text', 'Text')], default='numeric', max_length=20),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.testgroup'),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='manager.patient'),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='lab_request_qr/'),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('collected', 'Collected'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='lab_requests', to='laboratory.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('microbio', 'Microbiology'), ('other', 'Other')], default='blood', max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='ref_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ref_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='manager.patient'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='tube_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='observed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.testorder'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='manager.patient'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='ref_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='ref_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labrequest'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.sample'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.test'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='value_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='test',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tube_type',
        ),
        migrations.CreateModel(
            name='LabRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sample_qr', models.ImageField(blank=True, upload_to='lab_samples_qr/')),
                ('tube_prepared_at', models.DateTimeField(blank=True, null=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('sample_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('sample_received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_lab', 'In Lab'), ('measuring', 'Measuring'), ('review', 'In Review'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('value_num', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_min', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_max', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_bool', models.BooleanField(blank=True, default=None, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.labrequest')),
                ('sample_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_items_collected', to=settings.AUTH_USER_MODEL)),
                ('sample_dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_items_dispatched', to=settings.AUTH_USER_MODEL)),
                ('sample_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_items_received', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='laboratory.test')),
                ('tube_prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_items_tube_prep', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_items_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['test__english_name'],
                'unique_together': {('request', 'test')},
            },
        ),
    ]
