# Generated by Django 5.2.4 on 2025-08-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_labrequest_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
