# Generated by Django 5.2.4 on 2025-08-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_test_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_items', to='laboratory.testgroup', verbose_name='Test Group'),
        ),
    ]
