# Generated by Django 5.1.2 on 2025-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_relationships'),
        ('manager', '0005_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='manager.department'),
        ),
    ]
