# Generated by Django 5.2 on 2025-04-28 21:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_customuser_departments'),
        ('manager', '0005_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='staff',
        ),
        migrations.AddField(
            model_name='bonus',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bonus',
            name='staff',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['doctor', 'nurse', 'receptionist', 'pharmacist']}, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deduction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='deduction',
            name='staff',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['doctor', 'nurse', 'receptionist', 'pharmacist']}, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift_period',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('night', 'Night')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(choices=[('reward', 'Reward'), ('performance', 'Performance'), ('holiday', 'Holiday'), ('overtime', 'Overtime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='hr.payroll'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='deduction_type',
            field=models.CharField(choices=[('late_arrival', 'Late Arrival'), ('absence', 'Absence'), ('policy_violation', 'Policy Violation'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.payroll'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.department'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='per_patient_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
