# Generated by Django 5.2 on 2025-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_bonus_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attendance_method',
            field=models.CharField(blank=True, choices=[('fingerprint', 'Fingerprint'), ('facial_print', 'Facial Print'), ('login_logout', 'Log In and Log Out'), ('kpi', 'KPI-Based')], help_text='Individual attendance method; defaults to system setting if blank.', max_length=20, null=True),
        ),
    ]
