# Generated by Django 5.2.4 on 2025-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_customuser_attendance_method'),
        ('manager', '0021_patientreportsettings_show_ros_ent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='manager.department'),
        ),
    ]
