# Generated by Django 5.2.5 on 2025-08-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_customuser_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
