# Generated by Django 5.2.5 on 2025-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_customuser_qr_code_customuser_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('hospital_manager', 'Hospital manager'), ('hr', 'Human Resources'), ('technician', 'Technician')], default='hospital_manager', max_length=20),
        ),
    ]
