# Generated by Django 5.2.5 on 2025-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('hospital_manager', 'Hospital manager'), ('hr', 'Human Resources'), ('technician', 'Technician'), ('inventory_manager', 'Inventory Manager')], default='hospital_manager', max_length=20),
        ),
    ]
