"""
Django settings for patient_management project.

Generated by 'django-admin startproject' using Django 5.0.2.
"""

from pathlib import Path
import os
from django.urls import reverse_lazy




# ────────────────────────────  Paths  ──────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent     # …/core/../
LOCALE_PATHS = [BASE_DIR / "locale"]

# ────────────────────────────  Secrets / Env  ──────────────────────────────
ICD11_CLIENT_ID     = os.getenv(
    "ICD11_CLIENT_ID",
    "f40e689d-e9ab-4717-a89e-4436f97af713_6e89f527-3e07-4ca1-85ba-d04d4ec7f144"
)
ICD11_CLIENT_SECRET = os.getenv(
    "ICD11_CLIENT_SECRET",
    "0KpUfAq0x3Hg4CD3sYRRaKdiu5TLFZdZA75AJ1Yskng="
)

SECRET_KEY = "django-insecure-x$=eei$)z%*eglnvkc07h)t33g($7f(p44-)6p=74cj-j$y5oz"
DEBUG      = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "8a8d-156-195-60-98.ngrok-free.app",
    "hms-3wr2.onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://8a8d-156-195-60-98.ngrok-free.app",
    "https://hms-3wr2.onrender.com",
]

SITE_URL = "http://localhost:8000"

# ────────────────────────────  Installed apps  ────────────────────────────
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # your apps
    "superadmin",
    "hr",
    "manager",
    "staff",
    "general",
    'mptt',
    "laboratory",
    # 3rd‑party
    "widget_tweaks",
    "common_tags",
     'accounts',
     "rosetta",
      "activity",
    'maintenance',

]

AUTH_USER_MODEL = "hr.CustomUser"

# ────────────────────────────  Middleware  ────────────────────────────────
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
   
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
  


ROOT_URLCONF = "core.urls"

# ────────────────────────────  Templates  ─────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

#LOGIN_URL = 'hr:login'            # صفحة الدخول العامة
#LOGIN_REDIRECT_URL = 'core:home'        # احتياطي آمن بعد الدخول (صفحة ليست login)
#LOGOUT_REDIRECT_URL = 'hr:login'
LOGIN_URL            = reverse_lazy("superadmin:login")
LOGOUT_REDIRECT_URL  = reverse_lazy("superadmin:login")
# بعد تسجيل الدخول، وجّه المستخدمين إلى قائمة المرضى بدل المسار الافتراضي /accounts/profile/
LOGIN_REDIRECT_URL   = reverse_lazy("superadmin:dashboard")  # تم تغيير من manager إلى superadmin

WSGI_APPLICATION = "core.wsgi.application"

# ────────────────────────────  Database  ──────────────────────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ────────────────────────────  Password validation  ───────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ────────────────────────────  I18N / TZ  ─────────────────────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE     = "UTC"
USE_I18N      = True
USE_TZ        = True

LANGUAGES = (
    ("ar", "Arabic"),
    ("en", "English"),
)

# ────────────────────────────  Static / Media  ───────────────────────────
STATIC_URL = "/static/"

# The folder you created earlier (core/static/…)
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]

# Where collectstatic will copy files for production servers
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Path to the ICD‑11 Excel sheet—used by manager/icd_cache.py
ICD11_XLSX_PATH = BASE_DIR / "core" / "static" / "icd" / "icd11.xlsx"

# ────────────────────────────  Misc  ──────────────────────────────────────
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
