# Generated by Django 5.2 on 2025-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_attendance_method',
            field=models.CharField(choices=[('fingerprint', 'Fingerprint'), ('facial_print', 'Facial Print'), ('login_logout', 'Log In and Log Out'), ('kpi', 'KPI-Based')], default='fingerprint', help_text='Default attendance method for all employees unless overridden.', max_length=20),
        ),
    ]
