from django.urls import path
from .views import (
    StaffDetailView, StaffListView, StaffCreateView, StaffUpdateView, StaffDeleteView,
    StaffTaskCreateView, AttendanceListView, AttendanceCreateView,
    ScheduleListView, ScheduleCreateView, ScheduleUpdateView,
    ScheduleDetailView, ScheduleDeleteView, ShiftAssignmentListView,
    ShiftAssignmentCreateView, ShiftAssignmentUpdateView,
    ShiftAssignmentDeleteView, ShiftSwapRequestCreateView,
    ShiftSwapRequestListView, ShiftSwapApprovalView, staff_home,
    sync_attendance_from_zkteco, PayrollListView, PayrollCreateView,
    PayrollUpdateView, PayrollDeleteView, DeductionTypeListView,
    DeductionTypeCreateView, DeductionTypeUpdateView,
    DeductionTypeDeleteView, BonusTypeListView, BonusTypeCreateView,
    BonusTypeUpdateView, BonusTypeDeleteView, VacationPolicyListView,
    VacationPolicyCreateView, VacationPolicyUpdateView,
    VacationPolicyDeleteView, VacationBalanceListView,
    VacationBalanceCreateView, VacationBalanceUpdateView,
    VacationBalanceDeleteView, LeaveRequestListView,
    LeaveRequestCreateView, LeaveApprovalView, SystemSettingsUpdateView,
    GlobalBonusCreateView, GlobalDeductionCreateView
)
from .views import CommonLoginView

app_name = 'hr'

urlpatterns = [

    path('login/', CommonLoginView.as_view(), name='login'),

    path('', staff_home, name='staff_home'),  # ← الصفحة الرئيسية للموظفين
    path('staff/', StaffListView.as_view(), name='staff_list'),
    path('staff/<int:pk>/', StaffDetailView.as_view(), name='staff_detail'),
    path('staff/new/', StaffCreateView.as_view(), name='staff_create'),
    path('staff/<int:pk>/edit/', StaffUpdateView.as_view(), name='staff_edit'),
    path('staff/<int:pk>/delete/', StaffDeleteView.as_view(), name='staff_delete'),
    path('staff/task/new/', StaffTaskCreateView.as_view(), name='staff_task_create'),
    path('attendance/', AttendanceListView.as_view(), name='attendance_list'),
    path('attendance/new/', AttendanceCreateView.as_view(), name='attendance_create'),
    path('attendance/sync/', sync_attendance_from_zkteco, name='sync_attendance'),
    path('payroll/', PayrollListView.as_view(), name='payroll_list'),
    path('payroll/new/', PayrollCreateView.as_view(), name='payroll_create'),
    path('payroll/<int:pk>/edit/', PayrollUpdateView.as_view(), name='payroll_update'),
    path('payroll/<int:pk>/delete/', PayrollDeleteView.as_view(), name='payroll_delete'),
    path('payroll/bonus/create/', GlobalBonusCreateView.as_view(), name='global_bonus_create'),
    path('payroll/deduction/create/', GlobalDeductionCreateView.as_view(), name='global_deduction_create'),
    path('deduction-types/', DeductionTypeListView.as_view(), name='deduction_type_list'),
    path('deduction-types/new/', DeductionTypeCreateView.as_view(), name='deduction_type_create'),
    path('deduction-types/<int:pk>/edit/', DeductionTypeUpdateView.as_view(), name='deduction_type_update'),
    path('deduction-types/<int:pk>/delete/', DeductionTypeDeleteView.as_view(), name='deduction_type_delete'),
    path('bonus-types/', BonusTypeListView.as_view(), name='bonus_type_list'),
    path('bonus-types/new/', BonusTypeCreateView.as_view(), name='bonus_type_create'),
    path('bonus-types/<int:pk>/edit/', BonusTypeUpdateView.as_view(), name='bonus_type_update'),
    path('bonus-types/<int:pk>/delete/', BonusTypeDeleteView.as_view(), name='bonus_type_delete'),
    path('vacation-policies/', VacationPolicyListView.as_view(), name='vacation_policy_list'),
    path('vacation-policies/new/', VacationPolicyCreateView.as_view(), name='vacation_policy_create'),
    path('vacation-policies/<int:pk>/edit/', VacationPolicyUpdateView.as_view(), name='vacation_policy_update'),
    path('vacation-policies/<int:pk>/delete/', VacationPolicyDeleteView.as_view(), name='vacation_policy_delete'),
    path('vacation-balances/', VacationBalanceListView.as_view(), name='vacation_balance_list'),
    path('vacation-balances/new/', VacationBalanceCreateView.as_view(), name='vacation_balance_create'),
    path('vacation-balances/<int:pk>/edit/', VacationBalanceUpdateView.as_view(), name='vacation_balance_update'),
    path('vacation-balances/<int:pk>/delete/', VacationBalanceDeleteView.as_view(), name='vacation_balance_delete'),
    path('leave-requests/', LeaveRequestListView.as_view(), name='leave_request_list'),
    path('leave-requests/new/', LeaveRequestCreateView.as_view(), name='leave_request_create'),
    path('leave-requests/<int:pk>/approve/', LeaveApprovalView.as_view(), name='leave_approval'),
    path('schedules/', ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/new/', ScheduleCreateView.as_view(), name='schedule_create'),
    path('schedules/<int:pk>/', ScheduleDetailView.as_view(), name='schedule_detail'),
    path('schedules/<int:pk>/edit/', ScheduleUpdateView.as_view(), name='schedule_update'),
    path('schedules/<int:pk>/delete/', ScheduleDeleteView.as_view(), name='schedule_delete'),
    path('shifts/', ShiftAssignmentListView.as_view(), name='shift_assignment_list'),
    path('shifts/new/', ShiftAssignmentCreateView.as_view(), name='shift_assignment_create'),
    path('shifts/<int:pk>/edit/', ShiftAssignmentUpdateView.as_view(), name='shift_assignment_update'),
    path('shifts/<int:pk>/delete/', ShiftAssignmentDeleteView.as_view(), name='shift_assignment_delete'),
    path('shift-swaps/new/<int:shift_id>/', ShiftSwapRequestCreateView.as_view(), name='shift_swap_request_create'),
    path('shift-swaps/', ShiftSwapRequestListView.as_view(), name='shift_swap_request_list'),
    path('shift-swaps/<int:pk>/approve/', ShiftSwapApprovalView.as_view(), name='shift_swap_approval'),
    path('system-settings/hr/', SystemSettingsUpdateView.as_view(), name='hr_system_settings'),
]