# Generated by Django 5.2.4 on 2025-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('brief_description', models.TextField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('manufacture_company', models.CharField(max_length=100)),
                ('supplier_company', models.CharField(max_length=100)),
                ('maintenance_company', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('device_classification', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('device_usage', models.CharField(max_length=100)),
                ('technical_specifications', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('uses', models.TextField(blank=True, null=True)),
                ('complications_risks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
