# Generated by Django 5.2.4 on 2025-07-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('manager', '0015_visit_hospital_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='manager.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='half_life',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='manager.room'),
            preserve_default=False,
        ),
    ]
