# Generated by Django 5.2.4 on 2025-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_device_department_device_half_life_device_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_classification',
            field=models.CharField(choices=[('Airway Support Device', 'Airway Support Device'), ('Respiratory Support Device', 'Respiratory Support Device'), ('Circulatory Support Device', 'Circulatory Support Device'), ('Renal Support Device', 'Renal Support Device'), ('Surgical Device', 'Surgical Device'), ('Surgical Equipment', 'Surgical Equipment'), ('Feeding Device', 'Feeding Device'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
