# Generated by Django 5.2.4 on 2025-07-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_device_category_devicetransferrequest'),
        ('manager', '0015_visit_hospital_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetransferrequest',
            name='from_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='manager.room'),
        ),
    ]
