# Generated by Django 5.2.4 on 2025-07-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_devicetransferrequest_from_room'),
        ('manager', '0015_visit_hospital_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.bed'),
        ),
    ]
