# Generated by Django 5.2.4 on 2025-07-28 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_company_devicetype_deviceusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='هل متاح؟'),
        ),
        migrations.AddField(
            model_name='device',
            name='clean_status',
            field=models.CharField(choices=[('clean', 'نظيف'), ('needs_cleaning', 'يحتاج تنظيف'), ('unknown', 'غير محدد')], default='unknown', max_length=20, verbose_name='حالة النظافة'),
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('working', 'يعمل'), ('needs_maintenance', 'يحتاج صيانة'), ('broken', 'عطل دائم')], default='working', max_length=20, verbose_name='حالة الجهاز'),
        ),
        migrations.AddField(
            model_name='device',
            name='sterilization_status',
            field=models.CharField(choices=[('sterilized', 'معقم'), ('needs_sterilization', 'يحتاج تعقيم'), ('not_required', 'لا يحتاج تعقيم')], default='not_required', max_length=20, verbose_name='حالة التعقيم'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.devicetype', verbose_name='نوع الجهاز'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.deviceusage', verbose_name='استخدام الجهاز'),
        ),
        migrations.AlterField(
            model_name='device',
            name='maintenance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_devices', to='maintenance.company', verbose_name='شركة الصيانة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacture_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_devices', to='maintenance.company', verbose_name='شركة التصنيع'),
        ),
        migrations.AlterField(
            model_name='device',
            name='supplier_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_devices', to='maintenance.company', verbose_name='شركة التوريد'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نوع الجهاز'),
        ),
        migrations.AlterField(
            model_name='deviceusage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='استخدام الجهاز'),
        ),
    ]
