# Generated by Django 5.2.4 on 2025-07-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_device_availability_device_clean_status_and_more'),
        ('manager', '0015_visit_hospital_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.patient', verbose_name='المريض الحالي'),
        ),
        migrations.AddField(
            model_name='deviceusage',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='متوفر؟'),
        ),
        migrations.AddField(
            model_name='deviceusage',
            name='clean_status',
            field=models.CharField(choices=[('clean', 'نظيف'), ('needs_cleaning', 'يحتاج تنظيف'), ('unknown', 'غير محدد')], default='unknown', max_length=20, verbose_name='النظافة'),
        ),
        migrations.AddField(
            model_name='deviceusage',
            name='current_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_in_use', to='manager.patient', verbose_name='المريض الحالي'),
        ),
        migrations.AddField(
            model_name='deviceusage',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='قيد الاستخدام؟'),
        ),
        migrations.AddField(
            model_name='deviceusage',
            name='status',
            field=models.CharField(choices=[('working', 'يعمل'), ('needs_maintenance', 'يحتاج صيانة'), ('out_of_order', 'عطل دائم'), ('needs_check', 'يحتاج تفقد')], default='working', max_length=20, verbose_name='حالة الجهاز'),
        ),
        migrations.AddField(
            model_name='deviceusage',
            name='sterilization_status',
            field=models.CharField(choices=[('sterilized', 'معقم'), ('needs_sterilization', 'يحتاج تعقيم'), ('not_required', 'لا يحتاج تعقيم')], default='not_required', max_length=20, verbose_name='التعقيم'),
        ),
        migrations.AddField(
            model_name='deviceusage',
            name='usage_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بداية الاستخدام'),
        ),
        migrations.AlterField(
            model_name='device',
            name='clean_status',
            field=models.CharField(choices=[('clean', 'نظيف'), ('needs_cleaning', 'يحتاج تنظيف'), ('unknown', 'غير معروف')], default='unknown', max_length=20, verbose_name='حالة النظافة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('working', 'يعمل'), ('needs_maintenance', 'يحتاج صيانة'), ('out_of_order', 'عطل دائم'), ('needs_check', 'يحتاج تفقد')], default='working', max_length=20, verbose_name='حالة الجهاز'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sterilization_status',
            field=models.CharField(choices=[('sterilized', 'معقم'), ('needs_sterilization', 'يحتاج تعقيم'), ('unknown', 'غير معروف')], default='not_required', max_length=20, verbose_name='حالة التعقيم'),
        ),
    ]
