# Generated by Django 5.2.5 on 2025-08-21 21:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_devicecleaninglog_devicemaintenancelog_and_more'),
        ('manager', '0021_patientreportsettings_show_ros_ent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='device',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeviceUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('operation_type', models.CharField(choices=[('surgery', 'عملية جراحية'), ('transfer', 'نقل'), ('assignment', 'تخصيص'), ('maintenance', 'صيانة'), ('cleaning', 'تنظيف'), ('sterilization', 'تعقيم'), ('inspection', 'فحص'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع العملية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة؟')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.bed', verbose_name='السرير')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.department', verbose_name='القسم')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.patient', verbose_name='المريض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل استخدام الأجهزة',
                'verbose_name_plural': 'سجلات استخدام الأجهزة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.bed', verbose_name='السرير')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.patient', verbose_name='المريض')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة مسح',
                'verbose_name_plural': 'جلسات المسح',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_code', models.CharField(max_length=100, verbose_name='الكود الممسوح')),
                ('entity_type', models.CharField(max_length=50, verbose_name='نوع الكيان')),
                ('entity_id', models.IntegerField(verbose_name='معرف الكيان')),
                ('entity_data', models.JSONField(default=dict, verbose_name='بيانات الكيان')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المسح')),
                ('is_valid', models.BooleanField(default=True, verbose_name='صالح؟')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='رسالة الخطأ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='maintenance.scansession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'تاريخ المسح',
                'verbose_name_plural': 'تاريخ المسح',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceUsageLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المسح')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.device', verbose_name='الجهاز')),
                ('usage_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.deviceusagelog', verbose_name='سجل الاستخدام')),
            ],
            options={
                'verbose_name': 'عنصر سجل استخدام الجهاز',
                'verbose_name_plural': 'عناصر سجل استخدام الأجهزة',
                'unique_together': {('usage_log', 'device')},
            },
        ),
    ]
