# Generated by Django 5.2.5 on 2025-08-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_device_qr_code_device_qr_token_deviceusagelog_and_more'),
    ]

    operations = [
    ]
