# Generated by Django 5.2.5 on 2025-08-26 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_calibrationstandard_device_qr_code_device_qr_token_and_more'),
        ('manager', '0022_bed_qr_code_bed_qr_token_patient_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceusagelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل استخدام الأجهزة', 'verbose_name_plural': 'سجلات استخدام الأجهزة'},
        ),
        migrations.AlterModelOptions(
            name='deviceusagelogitem',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'عنصر سجل استخدام الجهاز', 'verbose_name_plural': 'عناصر سجل استخدام الأجهزة'},
        ),
        migrations.AlterUniqueTogether(
            name='deviceusagelog',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='devicecleaninglog',
            name='last_cleaned_by',
        ),
        migrations.RemoveField(
            model_name='devicemaintenancelog',
            name='last_maintained_by',
        ),
        migrations.RemoveField(
            model_name='devicesterilizationlog',
            name='last_sterilized_by',
        ),
        migrations.RemoveField(
            model_name='deviceusage',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='deviceusage',
            name='clean_status',
        ),
        migrations.RemoveField(
            model_name='deviceusage',
            name='current_patient',
        ),
        migrations.RemoveField(
            model_name='deviceusage',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='deviceusage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deviceusage',
            name='sterilization_status',
        ),
        migrations.RemoveField(
            model_name='deviceusage',
            name='usage_start_time',
        ),
        migrations.AddField(
            model_name='device',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='قيد الاستخدام؟'),
        ),
        migrations.AddField(
            model_name='device',
            name='usage_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بداية الاستخدام'),
        ),
        migrations.AddField(
            model_name='devicecleaninglog',
            name='cleaned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicecleaninglog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancelog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancelog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancelog',
            name='maintained_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicemaintenancelog',
            name='maintenance_type',
            field=models.CharField(choices=[('preventive', 'صيانة وقائية'), ('corrective', 'صيانة تصحيحية'), ('calibration', 'معايرة'), ('inspection', 'فحص')], default='preventive', max_length=50),
        ),
        migrations.AddField(
            model_name='devicemaintenancelog',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancelog',
            name='parts_replaced',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesterilizationlog',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicesterilizationlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesterilizationlog',
            name='sterilized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.bed', verbose_name='السرير'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='أكمل بواسطة'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='مكتملة؟'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='operation_type',
            field=models.CharField(choices=[('surgery', 'عملية جراحية'), ('transfer', 'نقل'), ('assignment', 'تخصيص'), ('maintenance', 'صيانة'), ('cleaning', 'تنظيف'), ('sterilization', 'تعقيم'), ('inspection', 'فحص'), ('procedure', 'إجراء طبي'), ('training', 'تدريب'), ('research', 'بحث'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الإجراء'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.room', verbose_name='الغرفة'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('paused', 'متوقف مؤقتًا')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='deviceusagelog',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceusagelogitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_log_items', to='maintenance.deviceaccessory', verbose_name='ملحق الجهاز'),
        ),
        migrations.AddField(
            model_name='deviceusagelogitem',
            name='issues_reported',
            field=models.TextField(blank=True, null=True, verbose_name='مشاكل مبلغ عنها'),
        ),
        migrations.AddField(
            model_name='deviceusagelogitem',
            name='status',
            field=models.CharField(choices=[('in_use', 'قيد الاستخدام'), ('completed', 'تم الاستخدام'), ('cancelled', 'تم الإلغاء'), ('paused', 'متوقف مؤقتًا')], default='in_use', max_length=20, verbose_name='حالة الاستخدام'),
        ),
        migrations.AddField(
            model_name='deviceusagelogitem',
            name='usage_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الاستخدام'),
        ),
        migrations.AddField(
            model_name='deviceusagelogitem',
            name='usage_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الاستخدام'),
        ),
        migrations.AddField(
            model_name='deviceusagelogitem',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_usages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='preventivemaintenanceschedule',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preventivemaintenanceschedule',
            name='day_of_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenanceschedule',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_calibrations', to='maintenance.device'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المعايرة'),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المعايرة التالية'),
        ),
        migrations.AlterField(
            model_name='calibrationstandard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationstandard',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationstandard',
            name='issuing_body',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='calibrationstandard',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='calibrationstandard',
            name='standard_number',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='sterilization_status',
            field=models.CharField(choices=[('sterilized', 'معقم'), ('needs_sterilization', 'يحتاج تعقيم'), ('not_required', 'لا يحتاج تعقيم')], default='not_required', max_length=20, verbose_name='حالة التعقيم'),
        ),
        migrations.AlterField(
            model_name='deviceaccessory',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم الملحق'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicedailyusagelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage_logs_old', to='maintenance.device'),
        ),
        migrations.AlterField(
            model_name='devicedowntime',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedowntime',
            name='reason',
            field=models.CharField(choices=[('breakdown', 'عطل'), ('maintenance', 'صيانة'), ('calibration', 'معايرة'), ('power_outage', 'انقطاع التيار'), ('operator_error', 'خطأ المشغل'), ('scheduled_downtime', 'توقف مجدول'), ('other', 'أخرى')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicedowntime',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_reported_downtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicedowntime',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_resolved_downtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicedowntime',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedowntime',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='maintenance.workorder'),
        ),
        migrations.AlterField(
            model_name='devicesubcategory',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='نوع الجهاز'),
        ),
        migrations.AlterField(
            model_name='deviceusage',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='استخدام الجهاز'),
        ),
        migrations.AlterField(
            model_name='deviceusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء'),
        ),
        migrations.AlterField(
            model_name='deviceusagelog',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='deviceusagelogitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب التوقف'),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='related_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_downtime_events', to='maintenance.workorder', verbose_name='أمر الشغل المرتبط'),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reported_downtimes', to=settings.AUTH_USER_MODEL, verbose_name='تم الإبلاغ بواسطة'),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_resolved_downtimes', to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة'),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بداية التوقف'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى الرسالة'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_email',
            field=models.EmailField(default='', max_length=254, verbose_name='بريد المستقبل'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(default='', max_length=300, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='failureanalysisreport',
            name='analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failureanalysisreport',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failureanalysisreport',
            name='failure_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failureanalysisreport',
            name='preventive_measures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failureanalysisreport',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف خطة العمل'),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الساعات المقدرة'),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='تعليمات العمل'),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم خطة العمل'),
        ),
        migrations.AlterField(
            model_name='jobplanstep',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الخطوة'),
        ),
        migrations.AlterField(
            model_name='jobplanstep',
            name='step_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الخطوة'),
        ),
        migrations.AlterField(
            model_name='jobplanstep',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان الخطوة'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مجدول لـ'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(blank=True, null=True, verbose_name='قالب المحتوى'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم القالب'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject_template',
            field=models.CharField(default='', max_length=300, verbose_name='قالب الموضوع'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenanceschedule',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم الجدولة'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenanceschedule',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق التالي'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenanceschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='entity_id',
            field=models.IntegerField(default=0, verbose_name='معرف الكيان'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='entity_type',
            field=models.CharField(default='', max_length=50, verbose_name='نوع الكيان'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='scanned_code',
            field=models.CharField(default='', max_length=100, verbose_name='الكود الممسوح'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المشكلة'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان البلاغ'),
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم الاتفاقية'),
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='resolution_time_hours',
            field=models.PositiveIntegerField(default=72, verbose_name='وقت الحل (ساعات)'),
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='response_time_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='وقت الاستجابة (ساعات)'),
        ),
        migrations.AlterField(
            model_name='slamatrix',
            name='impact',
            field=models.CharField(choices=[('extensive', 'واسع'), ('significant', 'كبير'), ('moderate', 'متوسط'), ('minor', 'بسيط')], default='moderate', max_length=20, verbose_name='التأثير'),
        ),
        migrations.AlterField(
            model_name='slamatrix',
            name='priority',
            field=models.CharField(choices=[('urgent', 'عاجل'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='slamatrix',
            name='severity',
            field=models.CharField(choices=[('critical', 'حرج'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20, verbose_name='درجة الخطورة'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='alternative_suppliers',
            field=models.ManyToManyField(blank=True, related_name='alternative_parts_v2', to='maintenance.supplier', verbose_name='الموردين البديلين'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم قطعة الغيار'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='part_number',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='رقم القطعة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='كود المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العمل'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان أمر العمل'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='رقم أمر العمل'),
        ),
        migrations.AlterField(
            model_name='workorderpart',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية المطلوبة'),
        ),
        migrations.AlterField(
            model_name='workorderpart',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة الإجمالية'),
        ),
        migrations.AlterField(
            model_name='workorderpart',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الوحدة'),
        ),
        migrations.CreateModel(
            name='DeviceUsageLogDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('shift', models.CharField(choices=[('morning', 'صباحي'), ('evening', 'مسائي'), ('night', 'ليلي')], default='morning', max_length=20, verbose_name='الوردية')),
                ('pre_use_check', models.BooleanField(default=False, verbose_name='تفقد ما قبل الاستخدام')),
                ('post_use_check', models.BooleanField(default=False, verbose_name='تفقد ما بعد الاستخدام')),
                ('operational_status', models.CharField(choices=[('working', 'يعمل بشكل طبيعي'), ('minor_issues', 'مشاكل بسيطة'), ('major_issues', 'مشاكل كبيرة'), ('not_working', 'لا يعمل')], default='working', max_length=20, verbose_name='حالة التشغيل')),
                ('usage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ساعات الاستخدام')),
                ('patient_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد المرضى')),
                ('issues_found', models.TextField(blank=True, verbose_name='المشاكل المكتشفة')),
                ('maintenance_needed', models.BooleanField(default=False, verbose_name='يحتاج صيانة')),
                ('cleaning_done', models.BooleanField(default=False, verbose_name='تم التنظيف')),
                ('sterilization_done', models.BooleanField(default=False, verbose_name='تم التعقيم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التفقد بواسطة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage_logs', to='maintenance.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل استخدام',
                'verbose_name_plural': 'سجلات الاستخدام',
                'ordering': ['-date', '-shift'],
                'unique_together': {('device', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.workorder')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceTransfer',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='cleaning_done',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='issues_found',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='maintenance_needed',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='operational_status',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='patient_count',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='post_use_check',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='pre_use_check',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='sterilization_done',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='deviceusagelog',
            name='usage_hours',
        ),
        migrations.CreateModel(
            name='DeviceTransfer',
            fields=[
            ],
            options={
                'verbose_name': 'Device Transfer',
                'verbose_name_plural': 'Device Transfers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('maintenance.devicetransferlog',),
        ),
    ]
