# Generated by Django 5.2.5 on 2025-08-21 22:08

from django.db import migrations


def populate_qr_tokens(apps, schema_editor):
    """Populate QR tokens for existing devices"""
    Device = apps.get_model('maintenance', 'Device')
    
    for device in Device.objects.filter(qr_token__isnull=True):
        device.qr_token = f"device:{device.pk}"
        device.save()


def reverse_populate_qr_tokens(apps, schema_editor):
    """Remove QR tokens"""
    Device = apps.get_model('maintenance', 'Device')
    Device.objects.update(qr_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_auto_20250822_0058'),
    ]

    operations = [
        migrations.RunPython(populate_qr_tokens, reverse_populate_qr_tokens),
    ]
