# Generated by Django 5.2.5 on 2025-08-27 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_deviceusagelog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر'), ('adjustment', 'تعديل'), ('return', 'إرجاع')], max_length=20, verbose_name='نوع المعاملة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('stock_before', models.PositiveIntegerField(verbose_name='المخزون قبل المعاملة')),
                ('stock_after', models.PositiveIntegerField(verbose_name='المخزون بعد المعاملة')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المعاملة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_transactions', to='maintenance.device', verbose_name='الجهاز')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='maintenance.sparepart', verbose_name='قطعة الغيار')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_transactions', to='maintenance.workorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'معاملة قطعة غيار',
                'verbose_name_plural': 'معاملات قطع الغيار',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['spare_part', '-transaction_date'], name='maintenance_spare_p_bc7c35_idx'), models.Index(fields=['transaction_type', '-transaction_date'], name='maintenance_transac_e856a1_idx')],
            },
        ),
    ]
