# Generated by Django 5.2.5 on 2025-08-27 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_spareparttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('reason', models.TextField(verbose_name='سبب الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('fulfilled', 'تم التنفيذ'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approval_notes', models.TextField(blank=True, verbose_name='ملاحظات الموافقة')),
                ('quantity_approved', models.PositiveIntegerField(blank=True, null=True, verbose_name='الكمية المعتمدة')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_spare_part_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_requests', to='maintenance.device', verbose_name='الجهاز')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_spare_part_requests', to=settings.AUTH_USER_MODEL, verbose_name='تم التنفيذ بواسطة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='maintenance.sparepart', verbose_name='قطعة الغيار')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='maintenance.spareparttransaction', verbose_name='المعاملة المرتبطة')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_requests', to='maintenance.workorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'طلب قطعة غيار',
                'verbose_name_plural': 'طلبات قطع الغيار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='maintenance_status_b131c8_idx'), models.Index(fields=['priority', '-created_at'], name='maintenance_priorit_60dffa_idx'), models.Index(fields=['requester', '-created_at'], name='maintenance_request_70f3a3_idx')],
            },
        ),
    ]
