# Generated by Django 5.2.5 on 2025-08-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_auto_20250822_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
