# Generated by Django 5.2.5 on 2025-08-21 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_alter_device_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qr_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DeviceAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_token', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الملحق')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الرقم التسلسلي')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموديل')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='الشركة المصنعة')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الضمان')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('in_use', 'قيد الاستخدام'), ('maintenance', 'تحت الصيانة'), ('damaged', 'تالف'), ('lost', 'مفقود')], default='available', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='maintenance.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'ملحق الجهاز',
                'verbose_name_plural': 'ملحقات الأجهزة',
                'ordering': ['name'],
            },
        ),
    ]
