# Generated by Django 5.2.5 on 2025-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_sparepartrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenanceschedule',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر إنجاز'),
        ),
    ]
