# Generated by Django 5.2.5 on 2025-08-22 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_alter_device_qr_token_deviceaccessory'),
        ('manager', '0022_bed_qr_code_bed_qr_token_patient_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHandoverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_logs', to='maintenance.device', verbose_name='الجهاز')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_handovers_from', to=settings.AUTH_USER_MODEL, verbose_name='من المستخدم')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_handovers_to', to=settings.AUTH_USER_MODEL, verbose_name='إلى المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تسليم الجهاز',
                'verbose_name_plural': 'سجلات تسليم الأجهزة',
                'ordering': ['-handed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النقل')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='maintenance.device', verbose_name='الجهاز')),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfers_from', to='manager.bed', verbose_name='من السرير')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfers_from', to='manager.department', verbose_name='من القسم')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfers_from', to='manager.room', verbose_name='من الغرفة')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نُقل بواسطة')),
                ('to_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfers_to', to='manager.bed', verbose_name='إلى السرير')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfers_to', to='manager.department', verbose_name='إلى القسم')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfers_to', to='manager.room', verbose_name='إلى الغرفة')),
            ],
            options={
                'verbose_name': 'سجل نقل الجهاز',
                'verbose_name_plural': 'سجلات نقل الأجهزة',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النقل')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_from', to='manager.bed', verbose_name='من السرير')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_from', to='manager.department', verbose_name='من القسم')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_from', to='manager.room', verbose_name='من الغرفة')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نُقل بواسطة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='manager.patient', verbose_name='المريض')),
                ('to_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_to', to='manager.bed', verbose_name='إلى السرير')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_to', to='manager.department', verbose_name='إلى القسم')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transfers_to', to='manager.room', verbose_name='إلى الغرفة')),
            ],
            options={
                'verbose_name': 'سجل نقل المريض',
                'verbose_name_plural': 'سجلات نقل المرضى',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAccessoryUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المسح')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.deviceaccessory', verbose_name='الملحق')),
                ('usage_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_items', to='maintenance.deviceusagelog', verbose_name='سجل الاستخدام')),
            ],
            options={
                'verbose_name': 'عنصر ملحق في سجل الاستخدام',
                'verbose_name_plural': 'عناصر الملحقات في سجل الاستخدام',
                'unique_together': {('usage_log', 'accessory')},
            },
        ),
    ]
