# Generated by Django 5.2.5 on 2025-08-30 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_add_last_completed_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم العملية')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز العملية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('auto_execute', models.BooleanField(default=True, verbose_name='تنفيذ تلقائي')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='يتطلب تأكيد')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=10, verbose_name='مهلة الجلسة (دقائق)')),
                ('allow_multiple_executions', models.BooleanField(default=True, verbose_name='السماح بتنفيذ متعدد')),
                ('log_to_usage', models.BooleanField(default=False, verbose_name='تسجيل في سجل الاستخدام')),
                ('log_to_transfer', models.BooleanField(default=False, verbose_name='تسجيل في سجل النقل')),
                ('log_to_handover', models.BooleanField(default=False, verbose_name='تسجيل في سجل التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تعريف العملية',
                'verbose_name_plural': 'تعريفات العمليات',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='devicetransfer',
            options={},
        ),
        migrations.AddField(
            model_name='scansession',
            name='context_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='سياق الجلسة'),
        ),
        migrations.AddField(
            model_name='scansession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر نشاط'),
        ),
        migrations.AddField(
            model_name='scansession',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='maintenance.operationdefinition', verbose_name='العملية الحالية'),
        ),
        migrations.CreateModel(
            name='OperationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('scanned_entities', models.JSONField(default=dict, help_text='Map of entity_type to entity data', verbose_name='الكيانات الممسوحة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات النتيجة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_logs', models.JSONField(blank=True, default=dict, help_text='References to logs created by this execution', verbose_name='السجلات المنشأة')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='منفذ العملية')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='maintenance.operationdefinition', verbose_name='العملية')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_executions', to='maintenance.scansession', verbose_name='جلسة المسح')),
            ],
            options={
                'verbose_name': 'تنفيذ العملية',
                'verbose_name_plural': 'تنفيذات العمليات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('entity_type', models.CharField(choices=[('user', 'مستخدم'), ('patient', 'مريض'), ('device', 'جهاز'), ('accessory', 'ملحق'), ('bed', 'سرير'), ('department', 'قسم'), ('room', 'غرفة'), ('lab_tube', 'أنبوب مختبر')], max_length=50, verbose_name='نوع الكيان')),
                ('is_required', models.BooleanField(default=True, verbose_name='مطلوب')),
                ('validation_rule', models.JSONField(blank=True, default=dict, help_text='JSON rules for validating the scanned entity', verbose_name='قواعد التحقق')),
                ('allowed_entity_ids', models.JSONField(blank=True, default=list, help_text='List of specific entity IDs allowed for this step', verbose_name='معرفات الكيانات المسموحة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الخطوة')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='maintenance.operationdefinition', verbose_name='العملية')),
            ],
            options={
                'verbose_name': 'خطوة العملية',
                'verbose_name_plural': 'خطوات العملية',
                'ordering': ['operation', 'order'],
                'unique_together': {('operation', 'entity_type'), ('operation', 'order')},
            },
        ),
    ]
