# Generated by Django 5.2.5

from django.db import migrations

def create_initial_operations(apps, schema_editor):
    """Create initial operation definitions for QR scanning system"""
    OperationDefinition = apps.get_model('maintenance', 'OperationDefinition')
    OperationStep = apps.get_model('maintenance', 'OperationStep')
    
    # Device Transfer Operation
    device_transfer_op = OperationDefinition.objects.create(
        name="Device Transfer",
        name_ar="نقل الجهاز",
        description="Transfer device between departments",
        description_ar="نقل الجهاز بين الأقسام",
        entity_types=['device', 'department'],
        requires_confirmation=True,
        auto_execute=False,
        timeout_minutes=30,
        log_to_transfer=True
    )
    
    OperationStep.objects.create(
        operation=device_transfer_op,
        step_number=1,
        instruction="Scan device QR code",
        instruction_ar="امسح رمز QR للجهاز",
        entity_type="device",
        is_required=True
    )
    
    OperationStep.objects.create(
        operation=device_transfer_op,
        step_number=2,
        instruction="Scan destination department QR code",
        instruction_ar="امسح رمز QR للقسم الجديد",
        entity_type="department",
        is_required=True
    )

def reverse_initial_operations(apps, schema_editor):
    """Remove initial operation definitions"""
    OperationDefinition = apps.get_model('maintenance', 'OperationDefinition')
    OperationDefinition.objects.filter(name="Device Transfer").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_operationdefinition_alter_devicetransfer_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_operations, reverse_initial_operations),
    ]