# Generated by Django 5.2.5 on 2025-08-23 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_devicehandoverlog_devicetransferlog_and_more'),
        ('manager', '0022_bed_qr_code_bed_qr_token_patient_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('handover', 'تسليم'), ('receipt', 'استلام'), ('transfer', 'نقل'), ('maintenance', 'صيانة'), ('return', 'إرجاع')], max_length=20, verbose_name='نوع العملية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('scanned_barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='الباركود الممسوح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='مؤكدة؟')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='maintenance.deviceaccessory', verbose_name='الملحق')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transactions_from', to='manager.department', verbose_name='من القسم')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transactions_from', to=settings.AUTH_USER_MODEL, verbose_name='من المستخدم')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transactions_to', to='manager.department', verbose_name='إلى القسم')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_transactions_to', to=settings.AUTH_USER_MODEL, verbose_name='إلى المستخدم')),
            ],
            options={
                'verbose_name': 'معاملة ملحق',
                'verbose_name_plural': 'معاملات الملحقات',
                'ordering': ['-created_at'],
            },
        ),
    ]
