# Generated by Django 5.2.5 on 2025-08-23 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_accessorytransaction'),
        ('manager', '0022_bed_qr_code_bed_qr_token_patient_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorytransaction',
            name='scanned_barcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الباركود الممسوح'),
        ),
        migrations.AlterField(
            model_name='accessorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('handover', 'تسليم'), ('receipt', 'استلام'), ('transfer', 'نقل'), ('maintenance', 'صيانة'), ('return', 'إرجاع')], default='handover', max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.CreateModel(
            name='AccessoryTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النقل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='maintenance.deviceaccessory', verbose_name='الملحق')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_logs_from', to='manager.department', verbose_name='من القسم')),
                ('from_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_logs_from', to='maintenance.device', verbose_name='من الجهاز')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_logs_from', to='manager.room', verbose_name='من الغرفة')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_logs_to', to='manager.department', verbose_name='إلى القسم')),
                ('to_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_logs_to', to='maintenance.device', verbose_name='إلى الجهاز')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_logs_to', to='manager.room', verbose_name='إلى الغرفة')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نُقل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل نقل ملحق',
                'verbose_name_plural': 'سجلات نقل الملحقات',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessoryTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب النقل')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه؟')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='maintenance.deviceaccessory', verbose_name='الملحق')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_requests_from', to='manager.department', verbose_name='من القسم')),
                ('from_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfers_from', to='maintenance.device', verbose_name='من الجهاز')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfers_from', to='manager.room', verbose_name='من الغرفة')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfer_requests_to', to='manager.department', verbose_name='إلى القسم')),
                ('to_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfers_to', to='maintenance.device', verbose_name='إلى الجهاز')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_transfers_to', to='manager.room', verbose_name='إلى الغرفة')),
            ],
            options={
                'verbose_name': 'طلب نقل ملحق',
                'verbose_name_plural': 'طلبات نقل الملحقات',
                'ordering': ['-requested_at'],
            },
        ),
    ]
