# Generated by Django 5.2.5 on 2025-08-31 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_add_initial_operations'),
        ('manager', '0022_bed_qr_code_bed_qr_token_patient_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetransferrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'طلب نقل جهاز', 'verbose_name_plural': 'طلبات نقل الأجهزة'},
        ),
        migrations.RemoveField(
            model_name='devicetransferrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='acceptance_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات القبول'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_accepted_by', to=settings.AUTH_USER_MODEL, verbose_name='القابل'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الموافقة'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='device_checked',
            field=models.BooleanField(default=False, verbose_name='تم فحص الجهاز'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='device_cleaned',
            field=models.BooleanField(default=False, verbose_name='تم تنظيف الجهاز'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='device_sterilized',
            field=models.BooleanField(default=False, verbose_name='تم تعقيم الجهاز'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='from_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_requests_from', to='manager.bed', verbose_name='من السرير'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_requests', to='manager.patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='reason',
            field=models.CharField(choices=[('patient_need', 'احتياج المريض'), ('maintenance', 'للصيانة'), ('emergency', 'حالة طارئة'), ('routine_transfer', 'نقل روتيني'), ('department_request', 'طلب القسم'), ('other', 'أخرى')], default='routine_transfer', max_length=50, verbose_name='سبب النقل'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='reason_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل السبب'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_rejected_by', to=settings.AUTH_USER_MODEL, verbose_name='الرافض'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق - في انتظار الموافقة'), ('approved', 'موافق عليه - في انتظار القبول'), ('accepted', 'مقبول - تم النقل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='to_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_requests_to', to='manager.bed', verbose_name='إلى السرير'),
        ),
        migrations.AlterField(
            model_name='devicetransferlog',
            name='from_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_logs_from', to='manager.bed', verbose_name='من السرير'),
        ),
        migrations.AlterField(
            model_name='devicetransferlog',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_logs_from', to='manager.department', verbose_name='من القسم'),
        ),
        migrations.AlterField(
            model_name='devicetransferlog',
            name='from_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_logs_from', to='manager.room', verbose_name='من الغرفة'),
        ),
        migrations.AlterField(
            model_name='devicetransferlog',
            name='to_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_logs_to', to='manager.bed', verbose_name='إلى السرير'),
        ),
        migrations.AlterField(
            model_name='devicetransferlog',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_logs_to', to='manager.department', verbose_name='إلى القسم'),
        ),
        migrations.AlterField(
            model_name='devicetransferlog',
            name='to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_logs_to', to='manager.room', verbose_name='إلى الغرفة'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='الموافق'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='maintenance.device'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='from_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_requests_from', to='manager.department', verbose_name='من القسم'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='from_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='manager.room', verbose_name='من الغرفة'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='to_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_transfer_requests_to', to='manager.department', verbose_name='إلى القسم'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='manager.room', verbose_name='إلى الغرفة'),
        ),
        migrations.AddIndex(
            model_name='devicetransferrequest',
            index=models.Index(fields=['status', 'requested_at'], name='maintenance_status_eeb6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetransferrequest',
            index=models.Index(fields=['device', 'status'], name='maintenance_device__65bd60_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetransferrequest',
            index=models.Index(fields=['from_department', 'status'], name='maintenance_from_de_2c5d48_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetransferrequest',
            index=models.Index(fields=['to_department', 'status'], name='maintenance_to_depa_3491ac_idx'),
        ),
    ]
