# Generated by Django 5.2.5 on 2025-09-01 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_alter_devicetransferrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=500, verbose_name='كود QR')),
                ('entity_type', models.CharField(max_length=50, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(max_length=100, verbose_name='معرف الكيان')),
                ('entity_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الكيان')),
                ('device_type', models.CharField(choices=[('scanner', 'جهاز مسح مخصص'), ('mobile', 'هاتف محمول'), ('tablet', 'جهاز لوحي'), ('desktop', 'حاسوب مكتبي'), ('unknown', 'غير معروف')], default='unknown', max_length=20, verbose_name='نوع الجهاز')),
                ('scanner_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف جهاز المسح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('token_signature', models.CharField(blank=True, max_length=64, null=True, verbose_name='توقيع الرمز')),
                ('is_secure', models.BooleanField(default=False, verbose_name='رمز آمن')),
                ('is_ephemeral', models.BooleanField(default=False, verbose_name='رمز مؤقت')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الجلسة')),
                ('flow_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم التدفق')),
                ('flow_executed', models.BooleanField(default=False, verbose_name='تم تنفيذ التدفق')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المسح')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم المسح بواسطة')),
            ],
            options={
                'verbose_name': 'سجل مسح QR',
                'verbose_name_plural': 'سجلات مسح QR',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='maintenance_entity__4c469b_idx'), models.Index(fields=['scanned_by', 'scanned_at'], name='maintenance_scanned_5e20ff_idx'), models.Index(fields=['device_type', 'scanned_at'], name='maintenance_device__382537_idx'), models.Index(fields=['scanner_id'], name='maintenance_scanner_0aad3d_idx')],
            },
        ),
    ]
