# Generated by Django 5.2.5 on 2025-09-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_add_room_operations'),
        ('maintenance', '0021_add_secure_qr_fields'),
    ]

    operations = [
    ]
