# Generated by Django 5.2.5 on 2025-09-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_merge_20250901_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slamatrix',
            unique_together={('device_category', 'severity', 'impact', 'sla_definition')},
        ),
    ]
