# Generated by Django 5.2.5 on 2025-09-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_alter_slamatrix_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slamatrix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='slamatrix',
            name='resolution_time_hours',
            field=models.IntegerField(default=72, verbose_name='وقت الحل (ساعات)'),
        ),
        migrations.AddField(
            model_name='slamatrix',
            name='response_time_hours',
            field=models.IntegerField(default=24, verbose_name='وقت الاستجابة (ساعات)'),
        ),
        migrations.AlterField(
            model_name='slamatrix',
            name='sla_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.sladefinition', verbose_name='تعريف SLA الأساسي'),
        ),
        migrations.AlterUniqueTogether(
            name='slamatrix',
            unique_together={('device_category', 'severity', 'impact', 'priority', 'sla_definition')},
        ),
    ]
