# Generated by Django 5.2.5 on 2025-09-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_alter_slamatrix_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slamatrix',
            unique_together={('device_category', 'severity', 'impact', 'sla_definition')},
        ),
    ]
