# Generated by Django 5.2.5 on 2025-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_alter_slamatrix_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slamatrix',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='slamatrix',
            name='impact',
            field=models.CharField(choices=[('extensive', 'واسع'), ('significant', 'كبير'), ('moderate', 'متوسط'), ('minor', 'بسيط')], max_length=20, verbose_name='درجة التأثير'),
        ),
        migrations.AlterField(
            model_name='slamatrix',
            name='priority',
            field=models.CharField(choices=[('urgent', 'عاجل'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='slamatrix',
            name='severity',
            field=models.CharField(choices=[('critical', 'حرج'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], max_length=20, verbose_name='درجة الخطورة'),
        ),
        migrations.AlterUniqueTogether(
            name='slamatrix',
            unique_together={('device_category', 'severity', 'impact', 'priority', 'sla_definition')},
        ),
    ]
