# Generated by Django 5.2.5 on 2025-09-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_alter_slamatrix_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='pm_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='maintenance.preventivemaintenanceschedule', verbose_name='جدول الصيانة الوقائية'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='maintenance.servicerequest', verbose_name='البلاغ'),
        ),
    ]
