# Generated by Django 5.2.5 on 2025-09-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0027_workorder_pm_schedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetransferrequest',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_picked_up_by', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
        migrations.AddField(
            model_name='devicetransferrequest',
            name='pickup_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الاستلام'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='acceptance_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات القبول النهائي'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول النهائي'),
        ),
        migrations.AlterField(
            model_name='devicetransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق - في انتظار الموافقة'), ('approved', 'موافق عليه - جاهز للاستلام'), ('pending_pickup', 'في انتظار الاستلام'), ('accepted', 'مستلم - تم النقل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='operationdefinition',
            name='code',
            field=models.CharField(choices=[('DEVICE_USAGE', 'استخدام الجهاز - Device Usage'), ('DEVICE_TRANSFER', 'نقل الجهاز - Device Transfer'), ('PATIENT_TRANSFER', 'نقل المريض - Patient Transfer'), ('DEVICE_HANDOVER', 'تسليم الجهاز - Device Handover'), ('ACCESSORY_USAGE', 'استخدام الملحقات - Accessory Usage'), ('DEVICE_CLEANING', 'تنظيف الجهاز - Device Cleaning'), ('DEVICE_STERILIZATION', 'تعقيم الجهاز - Device Sterilization'), ('DEVICE_MAINTENANCE', 'صيانة الجهاز - Device Maintenance'), ('INVENTORY_CHECK', 'فحص المخزون - Inventory Check'), ('QUALITY_CONTROL', 'مراقبة الجودة - Quality Control'), ('CALIBRATION', 'معايرة الجهاز - Device Calibration'), ('INSPECTION', 'فحص الجهاز - Device Inspection'), ('CUSTOM', 'عملية مخصصة - Custom Operation')], max_length=50, unique=True, verbose_name='رمز العملية'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('breakdown', 'عطل'), ('preventive', 'صيانة وقائية'), ('inspection', 'فحص'), ('calibration', 'معايرة'), ('upgrade', 'ترقية'), ('installation', 'تركيب'), ('other', 'أخرى')], default='breakdown', max_length=20, verbose_name='نوع البلاغ'),
        ),
    ]
