# Generated by Django 5.2.5 on 2025-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_devicetransferrequest_picked_up_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetransferrequest',
            name='include_accessories',
            field=models.BooleanField(default=False, verbose_name='نقل الإكسسوارات مع الجهاز'),
        ),
    ]
