# Generated by Django 5.2.5 on 2025-09-09 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0029_devicetransferrequest_include_accessories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='responsible_type',
            field=models.CharField(blank=True, choices=[('doctor', 'دكتور'), ('nurse', 'ممرض'), ('technician', 'فني')], max_length=20, null=True, verbose_name='نوع المسؤول'),
        ),
        migrations.AddField(
            model_name='device',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_devices', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الجهاز'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenanceschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي'), ('after_use', 'بعد كل استخدام'), ('after_shift', 'بعد كل وردية'), ('custom', 'مخصص')], max_length=20, verbose_name='التكرار'),
        ),
    ]
