# Generated by Django 5.2.5 on 2025-09-10 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0030_add_responsible_fields_and_new_frequencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشارة')),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='كود QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شارة',
                'verbose_name_plural': 'الشارات',
            },
        ),
        migrations.CreateModel(
            name='CleaningCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cleaning/', verbose_name='صورة التنظيف')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.badge', verbose_name='الشارة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_cycles', to='maintenance.device', verbose_name='الجهاز')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دورة تنظيف',
                'verbose_name_plural': 'دورات التنظيف',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SterilizationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('autoclave', 'أوتوكلاف'), ('chemical', 'كيميائي'), ('gas', 'غاز'), ('radiation', 'إشعاع'), ('dry_heat', 'حرارة جافة'), ('other', 'أخرى')], default='autoclave', max_length=50, verbose_name='طريقة التعقيم')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الدفعة')),
                ('indicators', models.TextField(blank=True, verbose_name='المؤشرات')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='sterilization/before/', verbose_name='صورة قبل التعقيم')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='sterilization/after/', verbose_name='صورة بعد التعقيم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.badge', verbose_name='الشارة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sterilization_cycles', to='maintenance.device', verbose_name='الجهاز')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دورة تعقيم',
                'verbose_name_plural': 'دورات التعقيم',
                'ordering': ['-start_time'],
            },
        ),
    ]
