# Generated by Django 5.2.5 on 2025-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0031_badge_cleaningcycle_sterilizationcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdefinition',
            name='allowed_badges',
            field=models.ManyToManyField(blank=True, related_name='allowed_operations', to='maintenance.badge', verbose_name='البطاقات المسموح لها'),
        ),
        migrations.AddField(
            model_name='operationdefinition',
            name='requires_badge',
            field=models.BooleanField(default=False, verbose_name='يتطلب بطاقة'),
        ),
    ]
