# Generated by Django 4.2.7 on 2025-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0032_operationdefinition_allowed_badges_and_more'),
    ]

    operations = [
        # This migration was created to add badge fields to operations
        # but the fields may already exist, so we'll make it a no-op migration
    ]