# Generated by Django 5.2.5 on 2025-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0039_add_badge_fields_to_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdefinition',
            name='code',
            field=models.CharField(choices=[('BADGE_AUTH', 'مصادقة البطاقة - Badge Authentication'), ('DEVICE_USAGE', 'استخدام الجهاز مع مريض - Patient Association'), ('END_DEVICE_USAGE', 'إنهاء استخدام الجهاز - End Patient Usage'), ('DEVICE_TRANSFER', 'نقل الجهاز - Device Transfer'), ('PATIENT_TRANSFER', 'نقل المريض - Patient Transfer'), ('DEVICE_HANDOVER', 'تسليم واستلام - Handover'), ('ACCESSORY_USAGE', 'استخدام الملحقات - Accessory Usage'), ('DEVICE_CLEANING', 'بدء/إنهاء التنظيف - Cleaning Start/End'), ('DEVICE_STERILIZATION', 'بدء/إنهاء التعقيم - Sterilization Start/End'), ('MAINTENANCE_OPEN', 'فتح أمر صيانة - Open Maintenance WO'), ('MAINTENANCE_CLOSE', 'إغلاق أمر صيانة - Close Maintenance WO'), ('DEVICE_LENDING', 'إعارة الجهاز - Device Lending'), ('OUT_OF_SERVICE', 'إخراج من الخدمة - Out of Service'), ('INVENTORY_CHECK', 'فحص المخزون - Inventory Check'), ('QUALITY_CONTROL', 'مراقبة الجودة - Quality Control'), ('CALIBRATION', 'معايرة الجهاز - Device Calibration'), ('INSPECTION', 'تفقد الجهاز - Device Inspection'), ('AUDIT_REPORT', 'تدقيق وتقرير - Auditing & Reporting'), ('CUSTOM', 'عملية مخصصة - Custom Operation')], max_length=50, unique=True, verbose_name='رمز العملية'),
        ),
    ]
