# Generated by Django 5.2.5 on 2025-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0040_alter_operationdefinition_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansession',
            name='context_json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='سياق الجلسة'),
        ),
    ]
