# Generated by Django 5.2.5 on 2025-09-12 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0041_alter_scansession_context_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_in_custody', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول الحالي'),
        ),
        migrations.AddField(
            model_name='device',
            name='custody_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تسليم العهدة'),
        ),
        migrations.AddField(
            model_name='device',
            name='custody_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات العهدة'),
        ),
    ]
