# Generated by Django 5.2 on 2025-04-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_add_department_hospital'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='superadmin.hospital'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PDFSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, help_text='Text to display in the PDF header', max_length=200)),
                ('footer_text', models.CharField(blank=True, help_text='Text to display in the PDF footer', max_length=200)),
                ('header_image', models.ImageField(blank=True, help_text='Optional header image (e.g., hospital logo)', null=True, upload_to='pdf_headers/')),
                ('include_patient_details', models.BooleanField(default=True, help_text='Include patient personal information')),
                ('include_companion_info', models.BooleanField(default=True, help_text='Include companion information')),
                ('include_medical_records', models.BooleanField(default=True, help_text='Include medical records')),
                ('font_size', models.IntegerField(default=12, help_text='Font size for table text (8-16)')),
                ('table_border_color', models.CharField(default='grey', help_text="Border color (e.g., 'grey', 'black', 'blue')", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_settings', to='superadmin.hospital')),
            ],
            options={
                'verbose_name': 'PDF Setting',
                'verbose_name_plural': 'PDF Settings',
            },
        ),
    ]
