# Generated by Django 5.1.2 on 2025-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_department_hospital_pdfsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis_code',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='coded_elsewhere',
            field=models.TextField(blank=True, null=True, verbose_name='Coded Elsewhere'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='exclusions',
            field=models.TextField(blank=True, null=True, verbose_name='Exclusions'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='external_reference_link',
            field=models.URLField(blank=True, null=True, verbose_name='External Reference Link'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='foundation_uri',
            field=models.URLField(blank=True, null=True, verbose_name='Foundation URI'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='icd_chapter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ICD Chapter'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='icd_code',
            field=models.CharField(default=1, max_length=10, verbose_name='ICD Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='inclusions',
            field=models.TextField(blank=True, null=True, verbose_name='Inclusions'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='index_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Index Terms'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Diagnosis Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='postcoordination_options',
            field=models.TextField(blank=True, null=True, verbose_name='Postcoordination Options'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='related_maternal_codes',
            field=models.TextField(blank=True, null=True, verbose_name='Related Maternal Codes'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='related_perinatal_codes',
            field=models.TextField(blank=True, null=True, verbose_name='Related Perinatal Codes'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date_diagnosed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Diagnosed'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
