# Generated by Django 5.2 on 2025-04-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='allergic_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='history_limitation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hpi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='immunization_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='impression_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='interpretation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_decision',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='mrn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='nutritional_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='past_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='past_surgical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='physical_exam',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='present_at_bedside',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='professional_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='psychiatric_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='referral_source',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ros',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='soap_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='social_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='source_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
