# Generated by Django 5.2 on 2025-04-29 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_medicalrecord_allergic_history_medicalrecord_bmi_and_more'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emergency_type', models.CharField(help_text='e.g., Trauma, Cardiac, Pediatric', max_length=50)),
                ('location', models.CharField(blank=True, help_text='e.g., Building A, Floor 1', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Number of beds or patients')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.hospital')),
            ],
            options={
                'verbose_name': 'Emergency Department',
                'verbose_name_plural': 'Emergency Departments',
            },
        ),
        migrations.CreateModel(
            name='SurgicalOperationsDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surgical_type', models.CharField(help_text='e.g., Orthopedic, Neurosurgical, General', max_length=50)),
                ('location', models.CharField(blank=True, help_text='e.g., Building B, Operating Theater 2', max_length=100)),
                ('operating_rooms', models.PositiveIntegerField(default=1, help_text='Number of operating rooms')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.hospital')),
            ],
            options={
                'verbose_name': 'Surgical Operations Department',
                'verbose_name_plural': 'Surgical Operations Departments',
            },
        ),
    ]
