# Generated by Django 5.2 on 2025-05-08 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_emergencydepartment_surgicaloperationsdepartment'),
        ('superadmin', '0002_systemsettings_default_attendance_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacteriologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample_type', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=100)),
                ('filled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_filled', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PACS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('study_type', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('radiology_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='emergencydepartment',
            options={'verbose_name': 'Emergency Department'},
        ),
        migrations.AlterModelOptions(
            name='surgicaloperationsdepartment',
            options={'verbose_name': 'Surgical Operations Department'},
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='at_least_one_id_document',
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(choices=[('regular', 'سرير عادي'), ('icu', 'سرير عناية مركزة'), ('nicu', 'حضانة أطفال'), ('clinic_office', 'مكتب في العيادة الخارجية'), ('er_office', 'مكتب في عيادة الإسعاف')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='manager.room'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'مستخدم'), ('maintenance', 'تحت الصيانة'), ('cleaning', 'قيد التنظيف')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='coded_elsewhere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date_diagnosed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='exclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='external_reference_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='foundation_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='icd_chapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='index_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='postcoordination_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='related_maternal_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='related_perinatal_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencydepartment',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emergencydepartment',
            name='emergency_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencydepartment',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='followup',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='manager.prescription'),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='footer_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='pdf_headers/'),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='header_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='include_companion_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='include_medical_records',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='include_patient_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='table_border_color',
            field=models.CharField(default='grey', max_length=20),
        ),
        migrations.AlterField(
            model_name='surgicaloperationsdepartment',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surgicaloperationsdepartment',
            name='operating_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='surgicaloperationsdepartment',
            name='surgical_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(check=models.Q(('passport__isnull', False), ('id_card__isnull', False), _connector='OR'), name='patient_identification_document_provided'),
        ),
        migrations.AddField(
            model_name='bacteriologyresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
        migrations.AddField(
            model_name='form',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
        migrations.AddField(
            model_name='observation',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.hospital'),
        ),
        migrations.AddField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
        migrations.AddField(
            model_name='pacs',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
        migrations.AddField(
            model_name='program',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='manager.patient'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
        migrations.AddField(
            model_name='testorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient'),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='manager.testorder'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='manager.testorder'),
        ),
    ]
