# Generated by Django 5.2 on 2025-05-08 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_immunization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluidBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('intake_ml', models.FloatField(help_text='Total fluid intake in milliliters')),
                ('output_ml', models.FloatField(help_text='Total fluid output in milliliters')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_balances', to='manager.medicalrecord')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ObsToObs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstoobs_forms', to='manager.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Body temperature in °C', max_digits=4)),
                ('heart_rate', models.PositiveSmallIntegerField(help_text='Heart rate in beats per minute')),
                ('respiratory_rate', models.PositiveSmallIntegerField(help_text='Respiratory rate in breaths per minute')),
                ('systolic_bp', models.PositiveSmallIntegerField(help_text='Systolic blood pressure (mmHg)')),
                ('diastolic_bp', models.PositiveSmallIntegerField(help_text='Diastolic blood pressure (mmHg)')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(help_text='Oxygen saturation (%)')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='manager.medicalrecord')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
