# Generated by Django 5.2 on 2025-05-08 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_fluidbalance_obstoobs_vitalsign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='end_date',
            new_name='first_dose_date',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='visit',
        ),
        migrations.AddField(
            model_name='medication',
            name='barcode',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='number_of_doses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular')], default='oral', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.medication'),
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('prepared', 'Prepared by pharmacy'), ('dispensed', 'Handed to nurse'), ('administered', 'Given to patient')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('patient_barcode_scanned', models.BooleanField(default=False, help_text='True once patient wristband scanned')),
                ('medication_barcode_scanned', models.BooleanField(default=False, help_text='True once med barcode scanned')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_history', to='manager.prescription')),
            ],
            options={
                'ordering': ('-performed_at',),
            },
        ),
    ]
