# Generated by Django 5.2 on 2025-05-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_rename_end_date_prescription_first_dose_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='form',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular')], default='oral', max_length=20, null=True),
        ),
    ]
