# Generated by Django 5.2 on 2025-05-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_pharmacyrequest_prescriptionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='default_dosage',
            field=models.CharField(blank=True, help_text='Suggested dosage to auto-populate', max_length=100, null=True),
        ),
    ]
