# Generated by Django 5.2 on 2025-06-29 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_medication_default_dosage'),
        ('superadmin', '0002_systemsettings_default_attendance_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hospital',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.hospital'),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
