# Generated by Django 5.2.4 on 2025-08-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_visit_hospital_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicaloperationsdepartment',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.bed'),
        ),
        migrations.AddField(
            model_name='surgicaloperationsdepartment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='manager.room'),
        ),
    ]
