# Generated by Django 5.2.4 on 2025-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_surgicaloperationsdepartment_bed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(choices=[('regular', 'سرير عادي'), ('OT_table', 'طاولة عمليات'), ('recovery', 'سرير افاقة'), ('waiting', 'سرير انتظار عمليات'), ('icu', 'سرير عناية مركزة'), ('nicu', 'حضانة أطفال'), ('clinic_office', 'مكتب في العيادة الخارجية'), ('er_office', 'مكتب في عيادة الإسعاف')], max_length=20),
        ),
    ]
