# Generated by Django 5.2.4 on 2025-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_bed_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('patients_ROOM', 'غرفة مرضي'), ('rad_ROOM', 'غرفة اشعة'), ('cleaning_ROOM', 'غرفة نظافة'), ('path_ROOM', 'غرفة حمام'), ('store_ROOM', 'غرفة مخزن'), ('lab_ROOM', 'غرفة معمل'), ('regular_ROOM', 'غرفة عادية'), ('OT_room', 'غرفة عمليات'), ('recovery', 'غرفة إفاقة'), ('OT_waiting', 'غرفة انتظار عمليات'), ('icu_ROOM', 'غرفة عناية مركزة'), ('nicu_room', 'غرفة حضانة أطفال'), ('clinic_office', 'مكتب في العيادة الخارجية'), ('er_office', 'مكتب في عيادة الإسعاف')], default='regular', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'متاحة'), ('occupied', 'مستخدمة'), ('maintenance', 'تحت الصيانة'), ('cleaning', 'قيد التنظيف')], default='available', max_length=20),
        ),
    ]
