# Generated by Django 5.2.4 on 2025-08-09 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_vitalsign_taken_by'),
        ('superadmin', '0002_systemsettings_default_attendance_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_basic_info', models.BooleanField(default=True)),
                ('include_companion_info', models.BooleanField(default=True)),
                ('include_medical_records', models.BooleanField(default=True)),
                ('include_admission_info', models.BooleanField(default=True)),
                ('include_chief_complaints', models.BooleanField(default=True)),
                ('include_hpi', models.BooleanField(default=True)),
                ('include_ros', models.BooleanField(default=True)),
                ('include_histories', models.BooleanField(default=True)),
                ('include_physical_exam', models.BooleanField(default=True)),
                ('include_medical_decision', models.BooleanField(default=True)),
                ('include_interpretation', models.BooleanField(default=True)),
                ('include_impression_plan', models.BooleanField(default=True)),
                ('include_professional_srv', models.BooleanField(default=True)),
                ('include_patient_edu', models.BooleanField(default=True)),
                ('include_soap_note', models.BooleanField(default=True)),
                ('show_allergies', models.BooleanField(default=True)),
                ('show_source_history', models.BooleanField(default=False)),
                ('show_present_at_bedside', models.BooleanField(default=False)),
                ('show_referral_source', models.BooleanField(default=False)),
                ('show_history_limitation', models.BooleanField(default=False)),
                ('show_ros_constitutional', models.BooleanField(default=False)),
                ('show_past_medical_history', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_report_settings', to='superadmin.hospital')),
            ],
        ),
    ]
