# Generated by Django 5.2.4 on 2025-08-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_patientreportsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreportsettings',
            name='show_ros_ent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientreportsettings',
            name='show_ros_eye',
            field=models.BooleanField(default=False),
        ),
    ]
