# Generated by Django 5.2.5 on 2025-09-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_bed_qr_code_bed_qr_token_patient_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='room',
            name='qr_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
