# Generated by Django 5.2.5 on 2025-09-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_add_room_qr_fields'),
        ('manager', '0023_add_room_qr_fields'),
    ]

    operations = [
    ]
