# Generated by Django 5.2.5 on 2025-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_merge_0020_add_room_qr_fields_0023_add_room_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
